services:
  react-advice-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8080:5173"
    networks:
      - react_advice_network

networks:
  react_advice_network:
